import { TUserDetails } from "../_types";

export const DUMMY_USERS: TUserDetails[] = [
    {
      id: "651893ec6cc91bed644e5afb",
      name: "Amie French",
      email: "amiefrench@reversus.com",
      phoneNumber: "+234 (881) 567-2829",
      dateJoined: "2014-04-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2018-01-27T06:00:40 -01:00",
      organizationId: "4",
      organization: {
        createdAt: "2023-09-20T11:26:59.741Z",
        name: "Metz LLC",
        id: "2",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Ellison",
      userTier: 2,
      account: {
        balance: 339480,
        accountNumber: 1910459784,
        bank: "Hometown",
      },
      personalInfo: {
        fullName: "Wilder Maxwell",
        phoneNumber: "+234 (936) 423-2696",
        emailAddress: "wildermaxwell@hometown.com",
        bvn: 5978974564,
        gender: "male",
        maritalStatus: "married",
        children: 1,
        typeOfResidence: "Parents Apartment",
      },
      educationAndEmployment: {
        levelOfEducation: "Phd",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Fin Tech",
        durationOfEmployment: "12 years",
        officialEmail: "wildermaxwell@hometown.com",
        monthlyIncome: 950774,
        loanRepayment: 60036,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Joan",
        },
        {
          name: "Facebook",
          link: "@Mueller_Collins",
        },
        {
          name: "Instagram",
          link: "@Wendi_Simmons",
        },
      ],
      guarantor: {
        fullName: "Elnora Wyatt",
        phoneNumber: "+234 (956) 594-3048",
        emailAddress: "elnorawyatt@hometown.com",
        relationship: "Cousin",
      },
    },
    {
      id: "651893ec03225464dd6c231c",
      name: "Little Fleming",
      email: "littlefleming@hometown.com",
      phoneNumber: "+234 (848) 507-3803",
      dateJoined: "2023-09-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2018-01-21T03:09:49 -01:00",
      organizationId: "1",
      organization: {
        createdAt: "2023-09-20T06:22:16.712Z",
        name: "Simonis - Hamill",
        id: "4",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Hilda",
      userTier: 3,
      account: {
        balance: 299054,
        accountNumber: 1279784165,
        bank: "Kyaguru",
      },
      personalInfo: {
        fullName: "Hart Olsen",
        phoneNumber: "+234 (818) 436-3142",
        emailAddress: "hartolsen@kyaguru.com",
        bvn: 6169868125,
        gender: "male",
        maritalStatus: "single",
        children: 6,
        typeOfResidence: "2 Bedroom",
      },
      educationAndEmployment: {
        levelOfEducation: "Phd",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Agriculture",
        durationOfEmployment: "2 years",
        officialEmail: "hartolsen@kyaguru.com",
        monthlyIncome: 975776,
        loanRepayment: 57537,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Parker",
        },
        {
          name: "Facebook",
          link: "@Faith_Hahn",
        },
        {
          name: "Instagram",
          link: "@Maxwell_Campbell",
        },
      ],
      guarantor: {
        fullName: "Earline Huff",
        phoneNumber: "+234 (838) 434-3303",
        emailAddress: "earlinehuff@kyaguru.com",
        relationship: "Sister",
      },
    },
    {
      id: "651893ec9f7cdb6558283ea7",
      name: "Earnestine Levine",
      email: "earnestinelevine@kyaguru.com",
      phoneNumber: "+234 (968) 500-2836",
      dateJoined: "2023-09-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2017-01-04T07:45:05 -01:00",
      organizationId: "4",
      organization: {
        createdAt: "2023-09-20T11:26:59.741Z",
        name: "Metz LLC",
        id: "2",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Coleman",
      userTier: 1,
      account: {
        balance: 210214,
        accountNumber: 1779309363,
        bank: "Zytrac",
      },
      personalInfo: {
        fullName: "Sarah Pitts",
        phoneNumber: "+234 (997) 414-2931",
        emailAddress: "sarahpitts@zytrac.com",
        bvn: 6811562145,
        gender: "female",
        maritalStatus: "divorced",
        children: 4,
        typeOfResidence: "Parents Apartment",
      },
      educationAndEmployment: {
        levelOfEducation: "Masters",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Fin Tech",
        durationOfEmployment: "5 years",
        officialEmail: "sarahpitts@zytrac.com",
        monthlyIncome: 897700,
        loanRepayment: 50616,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Dale",
        },
        {
          name: "Facebook",
          link: "@Lakisha_Mckinney",
        },
        {
          name: "Instagram",
          link: "@Wilda_Waller",
        },
      ],
      guarantor: {
        fullName: "Conway Cohen",
        phoneNumber: "+234 (801) 472-2439",
        emailAddress: "conwaycohen@zytrac.com",
        relationship: "Cousin",
      },
    },
    {
      id: "651893ec77937f5c95bd721d",
      name: "Howard Chase",
      email: "howardchase@zytrac.com",
      phoneNumber: "+234 (807) 554-2358",
      dateJoined: "2017-05-19T09:11:56 -01:00",
      status: "blacklisted",
      dob: "2019-03-23T03:51:39 -01:00",
      organizationId: "1",
      organization: {
        createdAt: "2023-09-20T06:22:16.712Z",
        name: "Simonis - Hamill",
        id: "4",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Bertie",
      userTier: 1,
      account: {
        balance: 459289,
        accountNumber: 1125589716,
        bank: "Zaggles",
      },
      personalInfo: {
        fullName: "Cain Keith",
        phoneNumber: "+234 (898) 469-3285",
        emailAddress: "cainkeith@zaggles.com",
        bvn: 5730741662,
        gender: "male",
        maritalStatus: "married",
        children: 4,
        typeOfResidence: "Parents Apartment",
      },
      educationAndEmployment: {
        levelOfEducation: "B.sc",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Farming",
        durationOfEmployment: "5 years",
        officialEmail: "cainkeith@zaggles.com",
        monthlyIncome: 910326,
        loanRepayment: 80628,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Bettie",
        },
        {
          name: "Facebook",
          link: "@Meyer_Davenport",
        },
        {
          name: "Instagram",
          link: "@Glenna_Hamilton",
        },
      ],
      guarantor: {
        fullName: "Villarreal Taylor",
        phoneNumber: "+234 (854) 493-2610",
        emailAddress: "villarrealtaylor@zaggles.com",
        relationship: "Nephew",
      },
    },
    {
      id: "651893ec7b44574e7d7ceac6",
      name: "Estelle Kane",
      email: "estellekane@zaggles.com",
      phoneNumber: "+234 (949) 507-3768",
      dateJoined: "2023-09-19T09:11:56 -01:00",
      status: "blacklisted",
      dob: "2014-04-21T02:25:06 -01:00",
      organizationId: "4",
      organization: {
        createdAt: "2023-09-20T06:22:16.712Z",
        name: "Simonis - Hamill",
        id: "4",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Mayra",
      userTier: 4,
      account: {
        balance: 547379,
        accountNumber: 1363189833,
        bank: "Printspan",
      },
      personalInfo: {
        fullName: "Guzman Hardin",
        phoneNumber: "+234 (974) 573-3344",
        emailAddress: "guzmanhardin@printspan.com",
        bvn: 5097491330,
        gender: "male",
        maritalStatus: "single",
        children: 6,
        typeOfResidence: "Hostel",
      },
      educationAndEmployment: {
        levelOfEducation: "Phd",
        employmentStatus: "employed",
        sectorOfEmployment: "Farming",
        durationOfEmployment: "12 years",
        officialEmail: "guzmanhardin@printspan.com",
        monthlyIncome: 979461,
        loanRepayment: 31172,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Warren",
        },
        {
          name: "Facebook",
          link: "@Stein_Randolph",
        },
        {
          name: "Instagram",
          link: "@Charlotte_Klein",
        },
      ],
      guarantor: {
        fullName: "Phyllis Knight",
        phoneNumber: "+234 (941) 492-3394",
        emailAddress: "phyllisknight@printspan.com",
        relationship: "Niece",
      },
    },
    {
      id: "651893ec65ff01ec8c4d9eb0",
      name: "Haynes Livingston",
      email: "hayneslivingston@printspan.com",
      phoneNumber: "+234 (926) 537-2817",
      dateJoined: "2017-05-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2018-09-16T09:30:59 -01:00",
      organizationId: "3",
      organization: {
        createdAt: "2023-09-20T11:26:59.741Z",
        name: "Metz LLC",
        id: "2",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Adele",
      userTier: 4,
      account: {
        balance: 163598,
        accountNumber: 1770722655,
        bank: "Accel",
      },
      personalInfo: {
        fullName: "West Ward",
        phoneNumber: "+234 (882) 529-2745",
        emailAddress: "westward@accel.com",
        bvn: 5673799088,
        gender: "female",
        maritalStatus: "single",
        children: 7,
        typeOfResidence: "Hostel",
      },
      educationAndEmployment: {
        levelOfEducation: "HND",
        employmentStatus: "employed",
        sectorOfEmployment: "Farming",
        durationOfEmployment: "12 years",
        officialEmail: "westward@accel.com",
        monthlyIncome: 821214,
        loanRepayment: 71836,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Nelson",
        },
        {
          name: "Facebook",
          link: "@Monroe_Mcneil",
        },
        {
          name: "Instagram",
          link: "@Sanchez_Kirk",
        },
      ],
      guarantor: {
        fullName: "Gilda Townsend",
        phoneNumber: "+234 (885) 424-2010",
        emailAddress: "gildatownsend@accel.com",
        relationship: "Niece",
      },
    },
    {
      id: "651893ecb1960c03a01a0fdf",
      name: "Gilbert Pierce",
      email: "gilbertpierce@accel.com",
      phoneNumber: "+234 (946) 481-3551",
      dateJoined: "2014-04-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2015-04-06T09:28:32 -01:00",
      organizationId: "1",
      organization: {
        createdAt: "2023-09-20T11:26:59.741Z",
        name: "Metz LLC",
        id: "2",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Rosie",
      userTier: 3,
      account: {
        balance: 442402,
        accountNumber: 1960737514,
        bank: "Bovis",
      },
      personalInfo: {
        fullName: "Katy Ashley",
        phoneNumber: "+234 (818) 561-3510",
        emailAddress: "katyashley@bovis.com",
        bvn: 5165913861,
        gender: "female",
        maritalStatus: "married",
        children: 5,
        typeOfResidence: "Hostel",
      },
      educationAndEmployment: {
        levelOfEducation: "Masters",
        employmentStatus: "employed",
        sectorOfEmployment: "Farming",
        durationOfEmployment: "12 years",
        officialEmail: "katyashley@bovis.com",
        monthlyIncome: 923077,
        loanRepayment: 32491,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Miranda",
        },
        {
          name: "Facebook",
          link: "@Guadalupe_Rush",
        },
        {
          name: "Instagram",
          link: "@Courtney_Brock",
        },
      ],
      guarantor: {
        fullName: "Fuller Harrell",
        phoneNumber: "+234 (888) 553-3862",
        emailAddress: "fullerharrell@bovis.com",
        relationship: "Sister",
      },
    },
    {
      id: "651893ec11d6687b7cb2c5d3",
      name: "Susie Alvarado",
      email: "susiealvarado@bovis.com",
      phoneNumber: "+234 (830) 468-3678",
      dateJoined: "2017-05-19T09:11:56 -01:00",
      status: "active",
      dob: "2014-02-25T01:17:00 -01:00",
      organizationId: "4",
      organization: {
        createdAt: "2023-09-20T05:57:54.585Z",
        name: "Satterfield - Dibbert",
        id: "1",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Hannah",
      userTier: 5,
      account: {
        balance: 280346,
        accountNumber: 1581390036,
        bank: "Yurture",
      },
      personalInfo: {
        fullName: "Irene Coffey",
        phoneNumber: "+234 (808) 417-2602",
        emailAddress: "irenecoffey@yurture.com",
        bvn: 5768879586,
        gender: "male",
        maritalStatus: "divorced",
        children: 3,
        typeOfResidence: "Hostel",
      },
      educationAndEmployment: {
        levelOfEducation: "Masters",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Agriculture",
        durationOfEmployment: "12 years",
        officialEmail: "irenecoffey@yurture.com",
        monthlyIncome: 744034,
        loanRepayment: 92623,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Shari",
        },
        {
          name: "Facebook",
          link: "@Margarita_Davidson",
        },
        {
          name: "Instagram",
          link: "@Sadie_Herrera",
        },
      ],
      guarantor: {
        fullName: "Jessica Velez",
        phoneNumber: "+234 (844) 469-2054",
        emailAddress: "jessicavelez@yurture.com",
        relationship: "Cousin",
      },
    },
    {
      id: "651893ecb28497f7d0f25340",
      name: "Dana Francis",
      email: "danafrancis@yurture.com",
      phoneNumber: "+234 (892) 419-2375",
      dateJoined: "2014-04-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2021-05-04T10:11:55 -01:00",
      organizationId: "2",
      organization: {
        createdAt: "2023-09-20T11:26:59.741Z",
        name: "Metz LLC",
        id: "2",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Pat",
      userTier: 5,
      account: {
        balance: 98031,
        accountNumber: 1159442408,
        bank: "Plutorque",
      },
      personalInfo: {
        fullName: "Twila Hunter",
        phoneNumber: "+234 (806) 430-2743",
        emailAddress: "twilahunter@plutorque.com",
        bvn: 4462990538,
        gender: "female",
        maritalStatus: "divorced",
        children: 3,
        typeOfResidence: "2 Bedroom",
      },
      educationAndEmployment: {
        levelOfEducation: "Phd",
        employmentStatus: "employed",
        sectorOfEmployment: "Farming",
        durationOfEmployment: "12 years",
        officialEmail: "twilahunter@plutorque.com",
        monthlyIncome: 976943,
        loanRepayment: 54839,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Vazquez",
        },
        {
          name: "Facebook",
          link: "@Rosa_Burton",
        },
        {
          name: "Instagram",
          link: "@Spence_Anderson",
        },
      ],
      guarantor: {
        fullName: "Holt Calderon",
        phoneNumber: "+234 (967) 406-2458",
        emailAddress: "holtcalderon@plutorque.com",
        relationship: "Brother",
      },
    },
    {
      id: "651893ec3a6374f39d7d4e98",
      name: "Kinney Palmer",
      email: "kinneypalmer@plutorque.com",
      phoneNumber: "+234 (907) 595-2125",
      dateJoined: "2017-05-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2017-04-17T07:06:52 -01:00",
      organizationId: "2",
      organization: {
        createdAt: "2023-09-20T05:57:54.585Z",
        name: "Satterfield - Dibbert",
        id: "1",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Hurst",
      userTier: 3,
      account: {
        balance: 121553,
        accountNumber: 1563827304,
        bank: "Rodeomad",
      },
      personalInfo: {
        fullName: "Meyers Owens",
        phoneNumber: "+234 (936) 458-3173",
        emailAddress: "meyersowens@rodeomad.com",
        bvn: 6774659113,
        gender: "male",
        maritalStatus: "divorced",
        children: 7,
        typeOfResidence: "Hostel",
      },
      educationAndEmployment: {
        levelOfEducation: "HND",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Agriculture",
        durationOfEmployment: "5 years",
        officialEmail: "meyersowens@rodeomad.com",
        monthlyIncome: 949778,
        loanRepayment: 45657,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Ollie",
        },
        {
          name: "Facebook",
          link: "@Hurley_Carver",
        },
        {
          name: "Instagram",
          link: "@Fernandez_Hayden",
        },
      ],
      guarantor: {
        fullName: "Madden Pena",
        phoneNumber: "+234 (946) 415-3538",
        emailAddress: "maddenpena@rodeomad.com",
        relationship: "Niece",
      },
    },
    {
      id: "651893ecfc43512eed57a229",
      name: "Lelia Pittman",
      email: "leliapittman@rodeomad.com",
      phoneNumber: "+234 (860) 408-2758",
      dateJoined: "2017-05-19T09:11:56 -01:00",
      status: "active",
      dob: "2017-09-18T12:56:05 -01:00",
      organizationId: "1",
      organization: {
        createdAt: "2023-09-20T02:04:18.608Z",
        name: "Torphy Inc",
        id: "3",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Laurel",
      userTier: 2,
      account: {
        balance: 102135,
        accountNumber: 1919247936,
        bank: "Zyple",
      },
      personalInfo: {
        fullName: "Sonia Wise",
        phoneNumber: "+234 (937) 431-3871",
        emailAddress: "soniawise@zyple.com",
        bvn: 4859423732,
        gender: "male",
        maritalStatus: "divorced",
        children: 6,
        typeOfResidence: "2 Bedroom",
      },
      educationAndEmployment: {
        levelOfEducation: "Phd",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Fin Tech",
        durationOfEmployment: "12 years",
        officialEmail: "soniawise@zyple.com",
        monthlyIncome: 906451,
        loanRepayment: 37756,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Alexis",
        },
        {
          name: "Facebook",
          link: "@Gentry_Nieves",
        },
        {
          name: "Instagram",
          link: "@Jennie_Melendez",
        },
      ],
      guarantor: {
        fullName: "Juliette Yates",
        phoneNumber: "+234 (867) 497-3878",
        emailAddress: "julietteyates@zyple.com",
        relationship: "Brother",
      },
    },
    {
      id: "651893ec435e6818795acc59",
      name: "Patrice Ballard",
      email: "patriceballard@zyple.com",
      phoneNumber: "+234 (993) 452-2978",
      dateJoined: "2014-04-19T09:11:56 -01:00",
      status: "blacklisted",
      dob: "2014-11-06T08:16:10 -01:00",
      organizationId: "3",
      organization: {
        createdAt: "2023-09-20T05:57:54.585Z",
        name: "Satterfield - Dibbert",
        id: "1",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Curry",
      userTier: 1,
      account: {
        balance: 490123,
        accountNumber: 1070526937,
        bank: "Dragbot",
      },
      personalInfo: {
        fullName: "Foster Jarvis",
        phoneNumber: "+234 (830) 425-3928",
        emailAddress: "fosterjarvis@dragbot.com",
        bvn: 5992453318,
        gender: "male",
        maritalStatus: "married",
        children: 2,
        typeOfResidence: "2 Bedroom",
      },
      educationAndEmployment: {
        levelOfEducation: "Phd",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Agriculture",
        durationOfEmployment: "12 years",
        officialEmail: "fosterjarvis@dragbot.com",
        monthlyIncome: 726234,
        loanRepayment: 72756,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Rena",
        },
        {
          name: "Facebook",
          link: "@Greer_Cash",
        },
        {
          name: "Instagram",
          link: "@Ramirez_Molina",
        },
      ],
      guarantor: {
        fullName: "Gwendolyn Larsen",
        phoneNumber: "+234 (873) 402-2981",
        emailAddress: "gwendolynlarsen@dragbot.com",
        relationship: "Brother",
      },
    },
    {
      id: "651893ec5db681355270886c",
      name: "Helena Mcbride",
      email: "helenamcbride@dragbot.com",
      phoneNumber: "+234 (965) 485-2243",
      dateJoined: "2017-05-19T09:11:56 -01:00",
      status: "inactive",
      dob: "2017-02-03T10:38:30 -01:00",
      organizationId: "4",
      organization: {
        createdAt: "2023-09-20T06:22:16.712Z",
        name: "Simonis - Hamill",
        id: "4",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Vickie",
      userTier: 3,
      account: {
        balance: 68522,
        accountNumber: 1373890073,
        bank: "Quonk",
      },
      personalInfo: {
        fullName: "Stanley Warren",
        phoneNumber: "+234 (804) 489-3383",
        emailAddress: "stanleywarren@quonk.com",
        bvn: 4923832379,
        gender: "female",
        maritalStatus: "single",
        children: 7,
        typeOfResidence: "Hostel",
      },
      educationAndEmployment: {
        levelOfEducation: "HND",
        employmentStatus: "employed",
        sectorOfEmployment: "Fin Tech",
        durationOfEmployment: "2 years",
        officialEmail: "stanleywarren@quonk.com",
        monthlyIncome: 751785,
        loanRepayment: 93926,
      },
      socials: [
        {
          name: "Twitter",
          link: "@May",
        },
        {
          name: "Facebook",
          link: "@Tiffany_Hess",
        },
        {
          name: "Instagram",
          link: "@Young_Gay",
        },
      ],
      guarantor: {
        fullName: "Mathews Ford",
        phoneNumber: "+234 (904) 521-3549",
        emailAddress: "mathewsford@quonk.com",
        relationship: "Cousin",
      },
    },
    {
      id: "651893ecf0aa03059b6efdb4",
      name: "Montgomery Acevedo",
      email: "montgomeryacevedo@quonk.com",
      phoneNumber: "+234 (983) 411-2578",
      dateJoined: "2010-01-19T09:11:56 -01:00",
      status: "active",
      dob: "2017-07-07T10:59:42 -01:00",
      organizationId: "4",
      organization: {
        createdAt: "2023-09-20T05:57:54.585Z",
        name: "Satterfield - Dibbert",
        id: "1",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Sweet",
      userTier: 3,
      account: {
        balance: 268708,
        accountNumber: 1678456987,
        bank: "Koffee",
      },
      personalInfo: {
        fullName: "Gill Justice",
        phoneNumber: "+234 (913) 443-2455",
        emailAddress: "gilljustice@koffee.com",
        bvn: 4318250211,
        gender: "male",
        maritalStatus: "single",
        children: 6,
        typeOfResidence: "Parents Apartment",
      },
      educationAndEmployment: {
        levelOfEducation: "HND",
        employmentStatus: "unemployed",
        sectorOfEmployment: "Farming",
        durationOfEmployment: "5 years",
        officialEmail: "gilljustice@koffee.com",
        monthlyIncome: 970840,
        loanRepayment: 41889,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Schmidt",
        },
        {
          name: "Facebook",
          link: "@Beasley_Meyer",
        },
        {
          name: "Instagram",
          link: "@Lester_Beard",
        },
      ],
      guarantor: {
        fullName: "Zimmerman Schwartz",
        phoneNumber: "+234 (886) 429-2050",
        emailAddress: "zimmermanschwartz@koffee.com",
        relationship: "Nephew",
      },
    },
    {
      id: "651893ecc2850a7a445a5f0b",
      name: "Annie Brown",
      email: "anniebrown@koffee.com",
      phoneNumber: "+234 (954) 464-3971",
      dateJoined: "2010-01-19T09:11:56 -01:00",
      status: "active",
      dob: "2020-02-29T07:00:15 -01:00",
      organizationId: "3",
      organization: {
        createdAt: "2023-09-20T11:26:59.741Z",
        name: "Metz LLC",
        id: "2",
      },
      image: "https://api.dicebear.com/7.x/adventurer/svg?seed=Amy",
      userTier: 1,
      account: {
        balance: 88602,
        accountNumber: 1826694359,
        bank: "Genmy",
      },
      personalInfo: {
        fullName: "Carlene House",
        phoneNumber: "+234 (822) 545-3885",
        emailAddress: "carlenehouse@genmy.com",
        bvn: 4832817697,
        gender: "female",
        maritalStatus: "single",
        children: 5,
        typeOfResidence: "Parents Apartment",
      },
      educationAndEmployment: {
        levelOfEducation: "HND",
        employmentStatus: "employed",
        sectorOfEmployment: "Agriculture",
        durationOfEmployment: "5 years",
        officialEmail: "carlenehouse@genmy.com",
        monthlyIncome: 752845,
        loanRepayment: 30604,
      },
      socials: [
        {
          name: "Twitter",
          link: "@Graciela",
        },
        {
          name: "Facebook",
          link: "@Arline_Roberts",
        },
        {
          name: "Instagram",
          link: "@Deirdre_Bentley",
        },
      ],
      guarantor: {
        fullName: "Tate Villarreal",
        phoneNumber: "+234 (983) 498-2015",
        emailAddress: "tatevillarreal@genmy.com",
        relationship: "Sister",
      },
    },
  ];